### ISSUE TITLE
Mudar o nome do arquivo gerado

### ISSUE THREAD

**Issue by edersoncosta** [CMCuritiba/wramais#25]
Trocar o nome genérico do relatório de ramais para "Lista de Ramais". Isso facilita em muito a localização e identificação do arquivo quando baixado.

**Comment by aleodoni** [comment]
Vou ver se é possível fazer isso; mas é o funcionamento padrão do browser

**Comment by edersoncosta** [comment]
Ok

**Comment by aleodoni** [comment]
Se setarmos o nome do relatório, o mesmo não é exibido, apenas opção para download. Acredito que seria melhor deixar como está. Vou fechar esta issue.
