### ISSUE TITLE
Cadastro relacionamento setor/local

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/wramais#27]
# Descrição
O sistema deverá prover uma tela para o relacionamento dos setores da CMC (vindos do sistema de elotech) e o local físico do mesmo.

## Requisito 1
A lista de setores deverá vir do serviço já existente que busca os mesmos do BD elotech

## Requisito 2
O relacionamento setor/endereço não é obrigatório

## Requisito 3
Caso exista, o relacionamento deverá ser 1-1

## Requisito 4
O campo local deverá ser do tipo string, tamanho máximo 500 caracteres

## Requisito 5
Somente usuários com permissão administrador poderá dar manutenção

**Comment by aleodoni** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CRUD relacionamento setor/local](https://trello.com/c/7KpePvRf/24-crud-relacionamento-setor-local)

**Comment by rodrigoferraro** [comment]
Eu não vejo praticidade sistêmica em prover forma de se inserir referido Local manualmente, acreditando que dentro da estrutura deve haver alguém responsável por manter tal controle sobre esta informação.
Atualmente temos nosso colega Tarcísio como responsável na telefonia, com disposição a realizar tal tarefa porém, em uma análise essencial, talvez não seja este o cargo mais apropriado a ser responsável por tal informação. O que você me diz @diemello, tem como inserir isso no Elotech?

**Comment by diemello** [comment]
Verificado no AISE (Elotech), e não existe a informação, nem campo para a adição do local físico.

Sugiro a adição da informação pelo **sistema de chamados**, possibilitando esta inclusão pelo Setor de Patrimônio ou DPSA

**Comment by DePorto** [comment]
Fechada para arquivamento.
