### ISSUE TITLE
Cadastro setores/ramais

### ISSUE THREAD

**Issue by aleodoni** [CMCuritiba/wramais#28]
# Descrição
Não haverá mais vínculo direto entre ramal/pessoa; os ramais serão relacionados com os setores. 

## Requisito 1
Um setor poderá ter vários ramais cadastrados

## Requisito 2
Cada registro terá os seguintes campos : 
* Setor
* Ramal
* Visível
* Chefia (identifica se o ramal é da chefia do setor)

## Requisito 3
Tela inicial deverá ter uma tabela com as seguintes colunas : 
* Setor (ordenado alfabeticamente default e link para alteração de dados)
* Ramal chefia
* Demais ramais
* Botão exclusão (este botão exclui todos os registros do setor - transação)
Abaixo da tabela deverá existir botão para incluir novo ramal

## Requisito 4
Tela de inclusão/alteração deverá ter:
* Combo setores ordenado alfabeticamente com opção de filtro
* Campos ramal, visível, chefia e deleta (este último em caso de alteração de dados)
* Botão (+) para adicionar mais uma linha
* Botão gravar que deverá gravar (única transação) todos os registros.

**Comment by aleodoni** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [CRUD Setores/Ramais](https://trello.com/c/tqcVCrqO/25-crud-setores-ramais)

**Comment by rodrigoferraro** [comment]
Verificado com @diemello que para se obter o cargo de, por exemplo, chefe de gabinete, é necessário permissão de acesso à view do Elotech beneficiario_crg_grupo, usado no portal.
Você pode solicitar essa permissão @diemello ?

**Comment by rodrigoferraro** [comment]
acabei escrevendo na issue #37 mais genericamente sobre essas associações.

**Comment by DePorto** [comment]
Fechada para arquivamento.
