### ISSUE TITLE
Ramais especiais

### ISSUE THREAD

**Issue by rodrigoferraro** [CMCuritiba/wramais#32]
Com a nova estrutura de ramais, sem vinculo com pessoa.. ainda existe a necessidade de Ramais_Especiais?

**Comment by rodrigoferraro** [comment]
Pelo que entendi conversando com Tarcísio, ainda será necessário existir essa estrutura, mesmo sem o vínculo à pessoa. Porque independente do vínculo, esses "setores", ou pessoas ainda serão necessários para permitir a pesquisa, como por exemplo, ao pesquisar "recepção anexo I" precisa retornar os ramais da referida recepção ainda que ela não exista no cadastro do Elotech.

**Comment by DePorto** [comment]
Fechada para arquivamento.
