### ISSUE TITLE
Consulta por apelido

### ISSUE THREAD

**Issue by rodrigoferraro** [CMCuritiba/wramais#36]
Tarcísio solicitou se há possibilidade de permitir consulta por apelidos, p.ex.: (toninho da farmácia ; katia animais de rua ; dpsa ; som ; etc)
Para o caso de vereadores tem a possibilidade de incluir os nomes políticos informados no SPL, porém para os setores também não vejo praticidade sistêmica em prover forma de se inserir referido Apelido manualmente.
Existe a possibilidade de relacionar esses apelidos no Elotech, @diemello ?

**Comment by diemello** [comment]
Para o caso dos vereadores, podemos verificar através do SPL. 
No AISE (Elotech) não temos esta informação de apelido cadastrada e também não temos a informação por nenhuma view. Poderiamos solicitar a inclusão, mas dependeríamos sempre de quem estiver cadastrando novos vereadores que sejam criados os apelidos no lugar correto.

> Certeza melhor usar o SPL. Não vale a pena inserir isso no Elotech, é fora do escopo dele, nome político é responsabilidade do SPL.. 

Não acho q seja tão prático para a consulta dos setor, mas podemos verificar a real necessidade destas informações.

> Legal, deixamos isso pra depois.

**Comment by DePorto** [comment]
Fechada para arquivamento.
