### ISSUE TITLE
Associação de Ramal (db - vereadores comissionados e efetivos)

### ISSUE THREAD

**Issue by rodrigoferraro** [CMCuritiba/wramais#37]
Tarcísio pediu a possibilidade de fazer associação de ramal diretamente à pessoa (raramente), ou a lotação (geral), ou ao cargo (diretorias e chefias). 
Cada ramal terá obrigatoriamente somente um desses vínculos, através do qual se obtém todas as outras relações.

**Comment by rodrigoferraro** [comment]
No que diz respeito aos cargos, verificando a view disponibilizada pela Elotech <v_cmcfuncionarios>, comecei a implementar uma auxiliar para informar o cargo de chefia de gabinete para os comissionados, mas preciso saber como identificar quando estes são chefes, para trazer somente o código para cargos de chefia. 
Ainda enquanto analisava os resultados da view que utilizava <*beneficiario_crg_grp>, confrontando com resultados da <v_cmcfuncionarios>, encontrei que esta view, que deveria trazer o código de cargos de chefia no campo <funcao>, não trouxe a informação preenchida para o "diretor da imprensa".
Sendo assim, visto que tem furos na view disponibilizada pela Elotech, e tem outras informações que eu preciso sejam complementadas nessa view, preciso que você @diemello solicite a Elotech correção e complementação da view <v_cmcfuncionarios>, acrescentando os cargos de chefias para os comissionados também.

**Comment by rodrigoferraro** [comment]
Hein @diemello, você acha melhor eu colocar os crg_id dos cargos de chefia dos comissionados pra filtrar (como você disse <aí preciso dos códigos>) - ou só coloco um filtro de texto na descrição trazendo todos os cargos de chefia e diretoria)?

**Comment by diemello** [comment]
Para os cargos comissionados pode utilizar o filtro por palavras chave de **cargo** (CHEFE, DIRETOR) e grp_id **3** em v_portal_beneficiario_crg_grp

**Comment by rodrigoferraro** [comment]
a view funcionarios no banco dos serviços, atualizada, ficou assim:

SELECT f.pessoa
	, f.matricula
	, f.pes_nome
	, CASE 
		WHEN f.ind_estagiario = 3 and cg.grp_id = 3 and (c.crg_nome ilike ''chefe%'' or c.crg_nome ilike ''diretor%'') THEN cg.crg_id::numeric
		ELSE f.funcao::numeric
	END AS funcao
	, f.set_id
	, f.ind_estagiario 
FROM aise.v_cmcfuncionarios f 
	inner join aise.v_portal_beneficiario_crg_grp cg 
		on f.matricula = cg.ben_id
	left outer join aise.v_cargo c 
		on cg.crg_id = c.crg_id
where cg.cbn_inicio <= CURRENT_DATE
	and cg.cbn_fim >= CURRENT_DATE

**Comment by rodrigoferraro** [comment]
O cargo dos vereadores da mesa vou pegar com outro serviço (do banco do spl), e para utilizá-los no "ramais", atualizo as informações destes cargos no resultSet da funcionarios...

**Comment by rodrigoferraro** [comment]
Criei a view no banco dos serviços (v_spl_cargos_mesa) para trazer somente os cargos da mesa.

**Comment by rodrigoferraro** [comment]
Para trazer o nome político dos vereadores, criei uma view que lista toda a tabela vereadores, fazendo join com o usuario somente para trazer a matricula. (v_spl_vereador)

**Comment by rodrigoferraro** [comment]
Informações sobre pessoa vem da v_cmcfuncionarios e da v_spl_vereador, os cargos dos efetivos vem tbm na v_cmcfuncionarios, agora abrangendo também os comissionados, e os cargos da mesa vem da v_spl_cargos_mesa, e os setores já vem na v_cmcfuncionarios.
Com isso parece que encerramos uma parte de banco para se obter os dados que serão associados aos ramais, bem como servirão à pesquisa.
