### ISSUE TITLE
Criar cadastro para ramais especiais

### ISSUE THREAD

**Issue by fderosso** [CMCuritiba/wramais#7]
Na lista de ramais também aparecem ramais que não estão atrelados a setores, são chamados de ramais especiais. ex:
Recepção do Prédio do Anexo I - 4911

**Comment by aleodoni** [comment]
![](https://github.trello.services/images/mini-trello-icon.png) [Criar cadastro de ramais especiais](https://trello.com/c/craghlT2/18-criar-cadastro-de-ramais-especiais)
